### ISSUE TITLE
Messages received with the new protocol are relayed to the old protocol

### ISSUE THREAD

**Issue by SuperTux88** [jaywink/social-relay#62]
The relay sends messages received via the new protocol to the legacy endpoint (with xml parameter and without `Content-Type` header). That fails now on diaspora and friendica. The new protocol doesn't have the `xml=` parameter anymore, and needs a `Content-Type: application/magic-envelope+xml` header, see [documentation](https://diaspora.github.io/diaspora_federation/federation/routes.html#public). All messages from diaspora 0.7.x (and I think also from the newest friendica release) fail now on all pods.

**Comment by jaywink** [comment]
I was under the understanding that support for receiving old style payloads was supposed to be supported for some time still? Wasn't it only that sending was changed to use the new style?

But sure, I'll tweak this tonight 👍

**Comment by SuperTux88** [comment]
Old style payloads are still supported, the problem is, that you send a new payload to the old endpoint, which doesn't work. There are some combinations possible where new stuff to the old endpoint work (for example when you use the new inner xml, but still have the old salmon wrapper, this works for diaspora, I don't know if it works for friendica), which maybe caused some confusion. But when sending the new salmon without the wrapper you need to send it to the new endpoint with `Content-Type` header and without the `xml` parameter.

**Comment by annando** [comment]
Great. When this works, I can remove my workaround that I created this morning.

**Comment by jaywink** [comment]
@annando I deployed a change to `relay.iliketoast.net`. I registered an account on jd that has no contacts and made a public post that arrived on [sechat](https://sechat.org/posts/2867969) at least.

Can you verify friendica side? Thanks

**Comment by annando** [comment]
Can you create a post with one of these hashtags? #piraten, #newhere, #frage

This then should arrive at my system. Please tell the guid, after you did the post, then I will have a look at the logfiles.

**Comment by jaywink** [comment]
@annando 82aea430845901359cb10242ac110007

**Comment by jaywink** [comment]
2017-09-25 22:56:23,510:DEBUG:network: send_document: url=https://pirati.ca/receive/public, ....
2017-09-25 22:56:24,501:DEBUG:network: send_document: response status code 200

**Comment by annando** [comment]
Works fine. Thanks for the fast reaction!

**Comment by jaywink** [comment]
Great, thanks for verifying! 👍 

Of course there is another relay relay.diasp.org that will push posts out with the old code for a while. I will do a release now and inform the relay owner to update.

**Comment by SuperTux88** [comment]
I just had a look at the fix, and this will now break posts from 0.6.x pods (the still send the old payload), since you now relay old payload to the new endpoint. Better would be when you see how you received a payload (old or new) and then send it the same way. But since most pods already upgraded I think the fix is enough, so thanks for the fast reaction.

**Comment by jaywink** [comment]
@SuperTux88 so diaspora doesn't just process a payload if delivered new or old style - it needs to be delivered *exactly the right way*? Huh, picky. That explains why my test post from Socialhome didn't go through.

I think this can stay closed. The relay is an extra service, those pods wanting to keep receiving all payloads should just start updating. I'll post a note out 👍 Have to remember to switch Socialhome over to new style delivery too.

**Comment by SuperTux88** [comment]
You could just ignore messages received from old pods here:

https://github.com/jaywink/social-relay/blob/master/social_relay/views.py#L113

Then you don't trigger a lot of errors everywhere, because these messages will now fail.

**Comment by jaywink** [comment]
Thanks I'll do that 👍

**Comment by SuperTux88** [comment]
> so diaspora doesn't just process a payload if delivered new or old style

The decision which salmon parser is used (if we need to parse the salmon wrapper) is made by which way we received it, after the salmon is parsed the salmon-payload (so the actual XML of the diaspora entity) is then decided via other ways (so it is more tolerant there, you can send a new salmon with old payload in it). But the outer salmon (magic env) parser decides with which way it was received.

> I think this can stay closed.

👍 

> those pods wanting to keep receiving all payloads should just start updating.

It's not about receiving here, it's about sending (so the sending podmins need to upgrade). Before the fix 0.7.x to **all** (0.6.x and 0.7.x) pods was broken, now after the fix 0.6.x to **all** pods is broken. Both old and new pods have the exact same receive logic, only sending changed to the new way. And because you combine all of these to one big pool and ignore how you received it, the target pods can't differentiate it anymore.
